### PR TITLE
feat: add 205, 208 and 226 statuses

### PR DESCRIPTION
**Pull request by lucasmezencio**
This PR introduces the 205, 208 and 226 status codes.

All the credit of this PR goes to @Xenofic! 💜

### CODE REVIEW

**Comment by lucasmezencio** [comment]
@rogeriopvl there you go! Muito obrigado! 🙂

**Comment by lucasmezencio** [comment]
@rogeriopvl any news? 🙂

**Comment by rogeriopvl** [comment]
Hi @lucasmezencio, sorry for the wait. Merging this now. Thanks!

**Comment by rogeriopvl** [comment]
@all-contributors add @lucasmezencio and @Xenofic for code

**Pull request merged**
