### PR TITLE
Add HTTP 521, 523, 525

### LINKED ISSUE #100: Missing image for code 521
Missing cat for status code 521 Web Server Down commonly used by the cloud flare service

### PR DESCRIPTION
**Pull request by fafrd**
Adding HTTP 521, 523, 525. These are cloudflare-specific status codes. Wikipedia covers their descriptions pretty well- https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#Cloudflare

Resolves #100, #93

images for status codes 521 and 523 were taken by me, I am releasing them into the public domain.

### CODE REVIEW

**Review by Dav-Git — APPROVED** [review]

**Comment by rogeriopvl** [comment]
Hi @fafrd 

Thanks for the PR, those look really cool! Can you make them follow the aspect ratio used in all other images?

**Comment by fafrd** [comment]
According to the readme, I can either follow the landscape or portrait ratios... I chose to go with portrait for these images.

I thought I did that correctly, I used the linked [template](https://docs.google.com/presentation/d/1Ay5nattHagPfnd-gMaUHumckFt2VANaYwMkXuQ-xS6E/edit#slide=id.p), replaced it w my own image and exported. Is this not correct?

**Review by edisim — APPROVED** [review]
LGTM

**Comment by rogeriopvl** [comment]
@fafrd nevermind. My bad, I looked at it in my smartphone and it seemed different from the template. I'm merging this now, but will only release it tomorrow or wednesday.

**Comment by CutiePi** [comment]
great images lol 🚀

**Comment by rogeriopvl** [comment]
@all-contributors add @fafrd for code

**Pull request merged**
