### PR TITLE
Add status code 308 (Permanent Redirect)

### LINKED ISSUE #15: Missing status: 308 Permanent Redirect
> [...] target resource has been assigned a new permanent URI and any future references to this resource ought to use one of the enclosed URIs.

https://tools.ietf.org/html/rfc7538

Or just reuse https://http.cat/301 because it's almost the same?

### PR DESCRIPTION
**Pull request by katrinleinweber**
Closes #15.

### CODE REVIEW

**Comment by rogeriopvl** [comment]
Hi @katrinleinweber 

Apologies for taking so long to approve this, and thanks for contributing 🙏 !

**Comment by rogeriopvl** [comment]
Released.

**Comment by katrinleinweber** [comment]
You're welcome & thanks for merging :-)

**Comment by rogeriopvl** [comment]
@all-contributors add @katrinleinweber for content

**Pull request merged**
