### PR TITLE
Add 103 early hints

### PR DESCRIPTION
**Pull request by CutiePi**
- [related 103 doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/103#on-github) 
- [wikipedia http code 1xx](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#1xx_informational_response)
- Just wanted to add my favorite cat 
- image is portrait in pr

I also made the image in the landscape if you prefer landscape see below

### CODE REVIEW

**Comment by CutiePi** [comment]
any problem with it? Can we merge ?

**Comment by CutiePi** [comment]
Hi @rogeriopvl, no worries about the late reply. 

I updated it to landscape, please let me know if anything is missing, have a good one! Cheers :)

**Comment by rogeriopvl** [comment]
Thanks @CutiePi

**Comment by rogeriopvl** [comment]
Deployed 🚀

**Comment by rogeriopvl** [comment]
@all-contributors add @CutiePi for code

**Pull request merged**
