### PR TITLE
Lazy load images to improve performance

### PR DESCRIPTION
**Pull request by AlexMayol**
Hello again! This PR aims to change the current usage of images by using Next's `<Image>` (so, a native `` tag) instead of a background image. This allows us to add `loading='lazy'` to the tag and lets the browser cache the result.

Current implementation - notice that all images are loaded once the page loads

https://github.com/httpcats/http.cat/assets/11309999/37743a08-6a69-4107-9d3a-42171cc9763f

New implementation - images are only loaded when user scrolls

https://github.com/httpcats/http.cat/assets/11309999/ded89301-590a-4590-b79b-a7cae487b7d9

I also removed the CSS module in favor of Tailwind and tried to achieve almose the same result in terms of layout.

✌🏻

### CODE REVIEW

**Comment by rogeriopvl** [comment]
Hi @AlexMayol 

Thanks for this great PR. I would love to merge it, but I noticed a breaking change that shouldn't happen. I'm seeing it in Firefox, running locally, but it's also visible in your video:

image

You can see it on Thumbnails that have a bit more text (ie. 203 status). All thumbnails should have same width and height.

**Comment by AlexMayol** [comment]
That's a good catch, @rogeriopvl !

I commited [a new change](https://github.com/httpcats/http.cat/pull/186/commits/8675f14e645401bbf275d1b7e7a997c9e6af1bfc) (just one Tailwind class 😉) so it should look like production:

Capture

**Comment by rogeriopvl** [comment]
@AlexMayol almost there! Check this video where I change from the production http.cat to a tab running locally, and you can see a slight zoom that makes the spacing just not quite right:

[Screencast from 11-21-2023 07:16:53 AM.webm](https://github.com/httpcats/http.cat/assets/38240/3876cb48-e895-49a6-8394-dd892a08df95)

**Comment by AlexMayol** [comment]
@rogeriopvl please, check it now. I think I nailed it this time 😄

**Comment by AlexMayol** [comment]
@rogeriopvl should I close this one?

**Comment by rogeriopvl** [comment]
@AlexMayol sorry for the delay. Looks pretty great now! Thanks!

**Pull request merged**
