### PR TITLE
Added 205, 208 and 226 status codes

### PR DESCRIPTION
**Pull request by Xenofic**
Addition of status codes mentioned in the list:-
1. https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/205
2. https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/208
3. https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/226

### CODE REVIEW

**Comment by rogeriopvl** [comment]
Hi @Xenofic

Thanks for the PR. The statuses to be added need to have an image associated.

**Comment by Xenofic** [comment]
@rogeriopvl Hey, I have added the images accordingly to the status codes

**Comment by lucasmezencio** [comment]
Up!

**Comment by lucasmezencio** [comment]
@Xenofic @rogeriopvl any news on this one?

**Comment by rogeriopvl** [comment]
@lucasmezencio @Xenofic The images are not using the required template (as mentioned in the README: https://github.com/httpcats/http.cat#adding-a-new-image)

**Comment by rogeriopvl** [comment]
Closed by #181

**Pull request closed without merging**
